logging:
  level:
    root: INFO
    com:
      vphan:
        microservices:
          siret-retrieval: DEBUG

management:
  endpoint:
    health:
      show-details: always

server:
  port: 9000

enterprise:
  baseUrl: https://entreprise.data.gouv.fr

db:
  fileLocation: ${DB_FILE_LOCATION}
